# Wayfare API Configuration

# Database
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME:postgres}
quarkus.datasource.password=${DB_PASSWORD:postgres}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/wayfarer}
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=true
quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true
quarkus.flyway.baseline-version=0

# Security (JWT)
mp.jwt.verify.issuer=https://wayfare.com
quarkus.smallrye-jwt.enabled=true
# For dev purposes, we can use the private key to sign and public key to verify
smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem

# API Versioning & Swagger
quarkus.smallrye-openapi.path=/api/openapi
quarkus.swagger-ui.path=/api/swagger
quarkus.swagger-ui.always-include=true

# Logging
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n
quarkus.log.level=INFO

# Mailer Configuration (Gmail requires an App Password)
quarkus.mailer.host=sandbox.smtp.mailtrap.io
quarkus.mailer.port=2525
quarkus.mailer.username=${MAILER_USERNAME}
quarkus.mailer.password=${MAILER_PASSWORD}
quarkus.mailer.from=${MAILER_FROM:noreply@wayfare.com}
quarkus.mailer.starttls=REQUIRED
quarkus.mailer.mock=false

# Admin Seeding
wayfare.admin.email=${ADMIN_EMAIL:admin@wayfare.com}
wayfare.admin.password=${ADMIN_PASSWORD:admin123}
